<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblAvailable</name>
   <tag></tag>
   <elementGuidId>1a22cbc8-5a2e-4b02-9bb9-af4dec6efa76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#availableBalance</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='availableBalance']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>70574cad-f965-46f4-9e5e-1c0ab86ee5a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>availableBalance</value>
      <webElementGuid>c14ca7b0-fb43-4980-a0c8-65551196de6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>b8e7b18d-e679-4d91-b37d-f1afbd60050e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$0.00</value>
      <webElementGuid>5414bf0e-1db9-4872-bc36-249213fd0623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;availableBalance&quot;)</value>
      <webElementGuid>d3632d9e-bbb7-431a-abca-adc90b79084a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='availableBalance']</value>
      <webElementGuid>303c266b-e93e-4743-9999-6f9e092ff65c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/table/tbody/tr[4]/td[2]</value>
      <webElementGuid>99bd0a15-b5b0-4360-8d1f-68f802c4ba2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]</value>
      <webElementGuid>cb4a1210-93df-4316-8368-7daa6a3d406c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'availableBalance' and (text() = '$0.00' or . = '$0.00')]</value>
      <webElementGuid>0ed7c7f3-7ebf-4043-b399-15d679b3b68a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
