<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblAccountNumber</name>
   <tag></tag>
   <elementGuidId>5cd52ffd-ecff-4b68-b247-e8ce17973ed8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accountId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='accountId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>85bc2d15-6f4b-4d45-95c2-d658991d448e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accountId</value>
      <webElementGuid>37744a9e-a87b-4dac-a901-c543c660545c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>86208de2-8575-40b2-9b89-9190934ed35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>13455</value>
      <webElementGuid>1a25f873-3c98-4296-936c-1ef4d4cbd927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accountId&quot;)</value>
      <webElementGuid>232aa8a8-5231-436f-b237-6f3b581f208d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='accountId']</value>
      <webElementGuid>c01b319d-3c01-4c54-a2e0-046f71c641c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/table/tbody/tr/td[2]</value>
      <webElementGuid>5b44520a-f419-4b9e-b296-03efbba9cce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>12276864-3f2a-41ea-9b41-c1149efb4784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'accountId' and (text() = '13455' or . = '13455')]</value>
      <webElementGuid>8fa25a61-a0ad-4d33-a224-baf078fc26d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
