<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblBalance</name>
   <tag></tag>
   <elementGuidId>a6c04467-1187-45ab-8b9c-e501c943f646</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#balance</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='balance']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>62b82402-d084-42db-9d9d-a93f0ac19c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>balance</value>
      <webElementGuid>e2ab68f9-c68e-4d38-a0d3-875b03f1132c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>2c7f2024-89b1-4b44-8559-217856a65358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-$2028,840,556.00</value>
      <webElementGuid>f26a4de6-20d9-46ff-91d5-1211fd2add8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;balance&quot;)</value>
      <webElementGuid>3b7dd749-532d-4b57-ad0d-55b65037f966</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='balance']</value>
      <webElementGuid>1892af7e-6786-4f84-8a62-5d289571a33f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/table/tbody/tr[3]/td[2]</value>
      <webElementGuid>8426f6b1-2818-4ab2-b88b-7a759c8121fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]</value>
      <webElementGuid>ce2a4b28-e3d1-47db-8021-b93de4c706e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'balance' and (text() = '-$2028,840,556.00' or . = '-$2028,840,556.00')]</value>
      <webElementGuid>50d11b5d-53a7-4f3b-a563-d0f41e055c83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
