<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblAccountAlreadyExists</name>
   <tag></tag>
   <elementGuidId>acedcca8-ba18-4b28-a8af-85e149b778e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rightPanel > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rightPanel']/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>3808eb60-a7b3-41d7-b510-6cf67a3aad59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>If you have an account with us you can sign-up for free instant online access. You will have to provide some personal information.</value>
      <webElementGuid>f173a0a5-47c9-4e0f-a103-b8389175f109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightPanel&quot;)/p[1]</value>
      <webElementGuid>288df8a0-b2e6-46d3-aee0-f6f95cf704e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/p</value>
      <webElementGuid>13ff89f4-2027-4930-99b4-341b8833ebf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>953b60d3-22d4-459f-a8f6-ea1562101a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'If you have an account with us you can sign-up for free instant online access. You will have to provide some personal information.' or . = 'If you have an account with us you can sign-up for free instant online access. You will have to provide some personal information.')]</value>
      <webElementGuid>fdc71538-4ec3-4530-b220-d8c95e76126a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
