<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblLoginInfoLookUpFailure</name>
   <tag></tag>
   <elementGuidId>b64f850e-001b-45f8-a7de-846228c52133</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rightPanel']/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d7460f42-e541-4a05-87c8-871a028a975c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>77c76725-f642-4305-8fd6-c382e69cb54a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The customer information provided could not be found.</value>
      <webElementGuid>56fa0a4c-241e-452b-b9dc-1ffbcef5763a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightPanel&quot;)/p[@class=&quot;error&quot;]</value>
      <webElementGuid>5d4cf0a4-0f38-4086-b26d-c60538b6c26d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/p</value>
      <webElementGuid>768abb48-db0c-4e76-9e45-2ae087e41e7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>3f87e1a1-1b83-423a-bcbd-2422d6811fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'The customer information provided could not be found.' or . = 'The customer information provided could not be found.')]</value>
      <webElementGuid>69249d44-258b-484c-a810-e6a7e04399dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
