<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblLoginInfoLookUpSuccess</name>
   <tag></tag>
   <elementGuidId>61df45c0-e702-4bf5-8fb1-3506c64b3d48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rightPanel > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rightPanel']/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>7aba384a-6647-4ee1-8dc4-1908ac8fdd89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your login information was located successfully. You are now logged in. </value>
      <webElementGuid>c1176ec7-ce8c-4399-a4c3-e3cbc947e675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightPanel&quot;)/p[1]</value>
      <webElementGuid>11e5ce2c-4ad3-413f-bfe5-1799d145dde4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/p</value>
      <webElementGuid>9bc33dc6-69a2-47dc-978a-bc95e93b4906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>349d1f84-6b57-441f-a6be-c8f737bf736c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Your login information was located successfully. You are now logged in. ' or . = 'Your login information was located successfully. You are now logged in. ')]</value>
      <webElementGuid>0f70988b-059f-4afe-95dc-79342309cbf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
