<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtSSN</name>
   <tag></tag>
   <elementGuidId>c5824f47-c8b1-4b48-86a2-4216fd62fbf3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ssn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ssn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>800869e0-a9e7-43c8-b808-81e67c5ff2c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ssn</value>
      <webElementGuid>e6a013a9-6309-4e10-917e-205853cef33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ssn</value>
      <webElementGuid>3edff5b5-f0cf-444c-8670-4bdf1c488f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>63c3f1ac-5ee1-4a2c-8b38-25d869fa21c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef0533b2-5200-4741-879c-af46246e73f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ssn&quot;)</value>
      <webElementGuid>e56ba870-6e4b-4267-ba8c-6b120e2d2003</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ssn']</value>
      <webElementGuid>fa88407c-4624-4b8b-a0bc-f775f14e6885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='lookupForm']/table/tbody/tr[7]/td[2]/input</value>
      <webElementGuid>724d1074-0781-4c82-acdf-27a54c7dc093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/input</value>
      <webElementGuid>a4e364cb-f52d-44c2-b520-148f76e658a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ssn' and @name = 'ssn' and @type = 'text']</value>
      <webElementGuid>50c8bf99-15d1-42d5-8cd2-3496ba4c830c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
