<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblAvailableBookstoreSOAPServices</name>
   <tag></tag>
   <elementGuidId>0fa4e37e-76c8-4607-837d-7cee7b772b5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rightPanel']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6e5f4630-35a7-4e22-a33a-c77f03fe8b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>fa9fb716-324a-462c-ab72-d04529b917a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Available Bookstore SOAP services:</value>
      <webElementGuid>d05bc9ff-236b-4c39-ab70-e1f017653725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightPanel&quot;)/span[@class=&quot;heading&quot;]</value>
      <webElementGuid>881d5457-0387-44ca-b9eb-029040447264</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/span</value>
      <webElementGuid>626af2fb-947a-401c-87d0-ba58faf569dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>4405013b-c754-4a6b-9991-0fe548006888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Available Bookstore SOAP services:' or . = 'Available Bookstore SOAP services:')]</value>
      <webElementGuid>8433d354-b976-4f67-b3bd-c0b4a287a74c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
