<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>All the test cases related to a new customer registration to the web application</description>
   <name>STS001 - A new customer registration verification</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>gkokabayeva@gmail.com;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>82ab423b-f74a-4a61-a0ae-913f132e78e9</testSuiteGuid>
   <testCaseLink>
      <guid>f82f22d7-cebd-40b9-9560-c57e14b03a68</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main Test Cases/MTC001 - User Registration</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f9c1bbd-49c4-4dcc-a8ec-aa0cb0e3fc62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1f06719-152c-4ebc-a5fc-f880ac57176c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ace93ef0-7105-4b5b-9dff-af68eb0363d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>493bb68a-a287-420a-bb5c-85869271feb2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77d37ee6-a4e3-400b-96d5-8a5b0fcb3475</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87d8e5d2-2795-4f73-8fd9-a18925fce3f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83e47582-b439-4007-b16e-be48e7dfbd8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fba1e0b7-5662-4f60-b8cb-3db193000b64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9bdd67a7-5561-4efb-88a8-f8e792cf36d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de2168f8-fef0-4b12-83ec-cd3edf6088ec</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
