<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>STS003 - Main page links verification</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>8ba874bd-28ae-4adf-a7c3-6713da20fd87</testSuiteGuid>
   <testCaseLink>
      <guid>65e1caa1-9751-4eec-b815-b5afc9d5836e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main Test Cases/MTC007 - Verify main page title</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8d4c256-de2b-448a-ac8c-3a545f6f35f9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>45185a34-e490-4308-b9c7-5f9158c523df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main Test Cases/MTC008 - Verify Services link</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf1b8abf-504d-4380-8421-9c484e5d5bba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>650ffb27-1ee1-406e-8741-9ebb8976adad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main Test Cases/MTC009 - Verify Products link</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>8b9fd6a0-bd69-40f5-9095-49aa482c5875</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main Test Cases/MTC010 - Verify Locations link</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2ccd782-a252-468e-a6c4-2df4b98619e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aede44d0-f3e9-4dc3-9f0e-97b3b7a948f1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8259c38f-e6a4-4565-9728-18128c654085</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main Test Cases/MTC011 - Verify Admin Page link</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79005dd7-ca78-4667-aee1-dcb8e91e24af</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7470d727-4952-45a7-bdcc-53c18506cfa6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main Test Cases/MTC012 - Verify About Us link</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8c86d21-e653-4905-a745-d4c36eb3a99f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e84236fc-c220-4298-a000-b3f0d198c4c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main Test Cases/MTC013 - Verify Home icon</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c74566e9-475f-4a6f-87aa-a0e1d1906020</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main Test Cases/MTC014 - Verify About icon</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f058952c-acfd-410b-ad57-ebe11e444430</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>224f33f8-2c90-4deb-bc58-d80b9b2f9217</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main Test Cases/MTC015 - Verify Contact icon</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94605798-a7d7-438b-b2f3-d1c8d6b167fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>95759cd2-2696-412f-9cde-d7f0dffb78f8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main Test Cases/MTC024 - Check latest news article 1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>147baba3-bff9-4b3c-8531-bc8f3b0eea2b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eb8120cf-2a50-4c51-8a45-946527f89921</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main Test Cases/MTC025 - Check latest news article 2</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca4dc510-e41d-48d7-aacb-e668699b5f5c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bce8a9ef-388d-4171-b029-13e156846065</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main Test Cases/MTC026 - Check latest news article 3</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1201bca6-1554-48f6-9202-45c531886a85</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
