<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iconHome</name>
   <tag></tag>
   <elementGuidId>19bfd065-112a-4eac-82c8-0c44d7686541</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.home > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headerPanel']/ul[2]/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0aaebe2a-e8b6-4fb2-8ff4-c0bfbb84ad61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/parabank/index.htm</value>
      <webElementGuid>8b1f64bc-7d17-44ac-a035-389929e51f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>home</value>
      <webElementGuid>ec4e5df3-7a9c-491b-926e-dd3c5d37e10e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerPanel&quot;)/ul[@class=&quot;button&quot;]/li[@class=&quot;home&quot;]/a[1]</value>
      <webElementGuid>df456b1f-c142-4365-8634-60d10ae77fdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headerPanel']/ul[2]/li/a</value>
      <webElementGuid>1c75464e-e0cf-4dee-8e55-4d8c0cc36b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'home')]</value>
      <webElementGuid>db00c33b-a253-46b9-a0ab-e09037993877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/parabank/index.htm')])[2]</value>
      <webElementGuid>36e7fbe6-808c-4df9-8792-1298ee6431ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li/a</value>
      <webElementGuid>41bca208-55fd-4646-9b75-30300529947c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/parabank/index.htm' and (text() = 'home' or . = 'home')]</value>
      <webElementGuid>d600582e-3fa4-4674-8426-bf06588cb2a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
