<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iconAbout</name>
   <tag></tag>
   <elementGuidId>dd6c8829-39c6-49c3-a2d6-8fabebf19966</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.aboutus > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headerPanel']/ul[2]/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>58cdc4c7-d90b-4006-9b8c-22aed6bacc0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>about.htm</value>
      <webElementGuid>0f751502-4619-465e-8535-d65bca66442b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>about</value>
      <webElementGuid>c9b7f1dc-7760-4e1f-b334-0960cc43315b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerPanel&quot;)/ul[@class=&quot;button&quot;]/li[@class=&quot;aboutus&quot;]/a[1]</value>
      <webElementGuid>014ccca2-5808-4b69-82b7-2bfa0e94f684</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headerPanel']/ul[2]/li[2]/a</value>
      <webElementGuid>c6901dd6-35c8-4832-9035-8cab8352c55c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'about')]</value>
      <webElementGuid>585848b0-8a20-42a4-9ce2-9edda594eb1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'about.htm')])[2]</value>
      <webElementGuid>36ce4867-9fb4-4a4f-b4f9-48eb45291eb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[2]/a</value>
      <webElementGuid>3d0c0ee1-ab90-4297-82f9-e35392dfd46a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'about.htm' and (text() = 'about' or . = 'about')]</value>
      <webElementGuid>e6b4ebcf-2a5a-4218-9d7b-bd31f626ef5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
