<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iconContact</name>
   <tag></tag>
   <elementGuidId>a6fb7086-7cf6-44c4-af56-9abb0c9b901d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.contact > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headerPanel']/ul[2]/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d75ab527-917d-495e-b418-0c4d67c27583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>contact.htm</value>
      <webElementGuid>cd2b7309-d87e-430e-9f92-a78c52c769f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>contact</value>
      <webElementGuid>1afe596f-962b-458f-b925-f6e7c0097983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerPanel&quot;)/ul[@class=&quot;button&quot;]/li[@class=&quot;contact&quot;]/a[1]</value>
      <webElementGuid>201ed7eb-af13-445c-9a4f-89cbba828bcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headerPanel']/ul[2]/li[3]/a</value>
      <webElementGuid>8d18e054-666c-4db2-9f11-4e7d1ec6db85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'contact')]</value>
      <webElementGuid>62fc6593-f22f-46a0-8f84-ef955ffde16d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'contact.htm')]</value>
      <webElementGuid>e46c108e-7365-40c1-a7a4-6e8f3e55fcf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[3]/a</value>
      <webElementGuid>870007da-e247-4177-9740-dcf6478bb18e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'contact.htm' and (text() = 'contact' or . = 'contact')]</value>
      <webElementGuid>a575245b-f41b-4cc7-9af2-be1bdd0ece22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
