<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lkRegister</name>
   <tag></tag>
   <elementGuidId>f0dc36dd-9574-4118-9bc5-20bf3075d61e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(2) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loginPanel']/p[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a251007b-a2f0-42df-be36-0769630b10b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>register.htm;jsessionid=87370EA7FD4B2F5AC034BE8AD5E20C94</value>
      <webElementGuid>95b6cd31-13a6-4697-8499-f1e2254c8b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>94581fcc-0df4-4604-8295-cfd4e517dbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginPanel&quot;)/p[2]/a[1]</value>
      <webElementGuid>5a6eebd4-159a-4cb6-9b7a-9785b5556bba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loginPanel']/p[2]/a</value>
      <webElementGuid>f11aa206-8842-465e-8c73-e0fcaa91fe9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Register')]</value>
      <webElementGuid>411a14a2-e2bf-41cb-8a00-2195f0d4b667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'register.htm;jsessionid=87370EA7FD4B2F5AC034BE8AD5E20C94')]</value>
      <webElementGuid>7a12d092-4727-4b6f-9c36-49c3b95a64de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a</value>
      <webElementGuid>72b7a00a-4142-46d3-a15f-e9fee1a84ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'register.htm;jsessionid=87370EA7FD4B2F5AC034BE8AD5E20C94' and (text() = 'Register' or . = 'Register')]</value>
      <webElementGuid>c3080873-c5db-4c09-afa4-4565415cd106</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
