<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkATMServices</name>
   <tag></tag>
   <elementGuidId>7220ea7a-6246-4e89-8c68-b7fedcd3ebd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.captionone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rightPanel']/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e3c3c195-a88f-4603-9b10-eac3e7aa7067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>captionone</value>
      <webElementGuid>694e46ef-9345-40fe-b7f5-67163039ceee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ATM Services</value>
      <webElementGuid>b5967d8f-7e73-4c16-9758-9f1164266726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightPanel&quot;)/ul[@class=&quot;services&quot;]/li[@class=&quot;captionone&quot;]</value>
      <webElementGuid>355937e7-acb0-47fd-9bcb-968dc0fd7a4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/ul/li</value>
      <webElementGuid>883970b1-b226-4b4e-87d4-372843081121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/ul/li</value>
      <webElementGuid>ba9e3571-07a5-407a-9cbe-8196ad5db5b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'ATM Services' or . = 'ATM Services')]</value>
      <webElementGuid>207080c3-64cd-4814-92dc-82f76b33fa85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
