<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkSolutions</name>
   <tag></tag>
   <elementGuidId>fba93fec-a2b3-4455-8f29-827fbd76d5ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.inner-banner-cont > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b622ebdd-e31f-467c-a0ef-848184283a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Solutions</value>
      <webElementGuid>09c30d87-030e-40ef-9425-d055852b7bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js&quot;]/body[@class=&quot;page-template-default page page-id-227 page-parent wp-embed-responsive preload group-blog innerpage webp-support&quot;]/section[@class=&quot;pad inner-banner  bgsecimg  alt-new&quot;]/div[@class=&quot;inner-banner-wrap&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-8 col-lg-8 col-md-8 col-sm-12&quot;]/div[@class=&quot;inner-banner-cont-wrap&quot;]/div[@class=&quot;inner-banner-cont&quot;]/span[1]</value>
      <webElementGuid>56c72ac6-b698-4cb9-b394-c685162dc33d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/span</value>
      <webElementGuid>c0c78d6c-0b0c-4eec-9d0f-d9fd4a4ec637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Solutions' or . = 'Solutions')]</value>
      <webElementGuid>355f386e-38c2-43d2-b6fe-d5a05749b94f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
