<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1ParaBankNews</name>
   <tag></tag>
   <elementGuidId>b0d509cf-a01d-4c71-9e6c-f25e4500eeec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rightPanel']/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>e5a70339-5a66-44c5-be19-753feb9aebee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>41da2106-deee-4072-b8c6-5c76df858601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ParaBank News</value>
      <webElementGuid>39079945-6ab5-4b82-b735-5cb13f0bcfd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightPanel&quot;)/h1[@class=&quot;title&quot;]</value>
      <webElementGuid>21342902-ae93-470a-a3bd-0f31e4504229</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/h1</value>
      <webElementGuid>214c981a-7720-4bbc-a054-a9488c81b71e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>02fa7809-cafa-409e-b33e-5490da9ba9e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'ParaBank News' or . = 'ParaBank News')]</value>
      <webElementGuid>b297a801-6e96-450a-ba9e-731564369692</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
