<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>errorStateIsRequiredMessage</name>
   <tag></tag>
   <elementGuidId>1c2c3a9e-343b-47be-abcf-33d909c83978</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.error.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rightPanel']/div/div/form/table/tbody/tr[5]/td[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5b338c1d-7e5d-407a-987c-f33fe7ebcd5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>customer &amp;&amp; !customer.address.state</value>
      <webElementGuid>a42affdf-bc65-4f4f-8975-3ce9b359f716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error ng-scope</value>
      <webElementGuid>92f8f11c-1a17-4a4b-a78d-583888b618b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>State is required.</value>
      <webElementGuid>2da7542d-bc01-4e97-a6fb-d181d637a715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightPanel&quot;)/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/form[@class=&quot;ng-valid ng-dirty ng-valid-parse ng-submitted&quot;]/table[@class=&quot;form2&quot;]/tbody[1]/tr[5]/td[3]/span[@class=&quot;error ng-scope&quot;]</value>
      <webElementGuid>47372c0b-564c-4420-be8e-1a79cc143ee6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/form/table/tbody/tr[5]/td[3]/span</value>
      <webElementGuid>68cae28f-5ba9-4597-81b2-35dbdfbd07e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>fe1e27b3-ea77-41b8-95af-c4cf5b3fed8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'State is required.' or . = 'State is required.')]</value>
      <webElementGuid>2b68bcae-d427-4c58-adc4-a1eeabb2638e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
