<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>errorAddressIsRequiredMessage</name>
   <tag></tag>
   <elementGuidId>703d6b15-1914-4ad0-a492-3a06db2f928f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.error.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rightPanel']/div/div/form/table/tbody/tr[3]/td[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>91dd6a55-d118-4eaf-bfca-861c9ec446ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>customer &amp;&amp; !customer.address.street</value>
      <webElementGuid>f891ba20-6697-481d-ab08-426441597223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error ng-scope</value>
      <webElementGuid>6e443eaa-32d8-4cfe-b1a2-cf8a6e95302c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Address is required.</value>
      <webElementGuid>f2f7fff0-9777-4cad-ac5d-e09d4e130494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightPanel&quot;)/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/form[@class=&quot;ng-valid ng-dirty ng-valid-parse ng-submitted&quot;]/table[@class=&quot;form2&quot;]/tbody[1]/tr[3]/td[3]/span[@class=&quot;error ng-scope&quot;]</value>
      <webElementGuid>6c77abe7-68d7-420a-b429-8f56a408297a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/form/table/tbody/tr[3]/td[3]/span</value>
      <webElementGuid>67d936ff-3d38-469b-b1e2-936e6d44485d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>e4c56fe3-283b-48a8-8bed-92bf0bba4ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Address is required.' or . = 'Address is required.')]</value>
      <webElementGuid>b5cef6fc-3ccb-4d23-ab3f-e1486604670b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
