<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lkAccount</name>
   <tag></tag>
   <elementGuidId>d2cc2170-00ca-4376-810b-014cfc1cd689</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='accountTable']/tbody/tr/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>16a11911-b54a-4580-8f7f-acb78c54edea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>activity.htm?id=13455</value>
      <webElementGuid>504e164d-37de-414e-8f16-6d7004737c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>4ca47511-4a2a-4aea-b1c8-f737b89ac113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>13455</value>
      <webElementGuid>d86feb48-3cad-49f1-8705-ba620f692fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accountTable&quot;)/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[1]/a[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>670709fa-c787-4354-bb4e-ca4f7de2fdae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='accountTable']/tbody/tr/td/a</value>
      <webElementGuid>cf4d09fc-1adb-4d67-bd6a-726c391b16ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'13455')]</value>
      <webElementGuid>d3a5811e-2016-473f-a9fb-00d3f8db165a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'activity.htm?id=13455')]</value>
      <webElementGuid>d7be6f78-66b8-4415-b1ec-6b553641e52f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>4f808906-e231-4207-9d74-006fba22c830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'activity.htm?id=13455' and (text() = '13455' or . = '13455')]</value>
      <webElementGuid>2997655c-46b4-4257-96c9-f06896ec88f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
