<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkOpenNewAccount</name>
   <tag></tag>
   <elementGuidId>68de0ed7-35e4-45e3-b4eb-3bdaad11f8bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leftPanel > ul > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='leftPanel']/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>80281b69-9eeb-463c-8ce1-5b425fae19c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/parabank/openaccount.htm</value>
      <webElementGuid>bb6dc6af-e716-46d7-8012-905a3c86a989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Open New Account</value>
      <webElementGuid>39a16bff-5467-41f5-82d4-8ff599231a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftPanel&quot;)/ul[1]/li[1]/a[1]</value>
      <webElementGuid>801143d8-6878-47bf-826d-a3757ba376fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftPanel']/ul/li/a</value>
      <webElementGuid>6eaca21f-68ce-48ff-856d-425c4b6edd30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Open New Account')]</value>
      <webElementGuid>4f8699d8-148b-41d6-b994-e33c03bae4d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/parabank/openaccount.htm')]</value>
      <webElementGuid>5c28e803-069b-4ce9-8b19-2b2a9057f3c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li/a</value>
      <webElementGuid>c0f9d445-4f21-419f-a2f7-5cdf5236694f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/parabank/openaccount.htm' and (text() = 'Open New Account' or . = 'Open New Account')]</value>
      <webElementGuid>c99260b4-aefc-4d70-b275-4d11f071b2db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
