<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1AccountOpened</name>
   <tag></tag>
   <elementGuidId>7affc53c-d163-45a7-a883-b9603ff7a9c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rightPanel']/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>45525321-fa29-41c9-8617-6a53065c413c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>d1b7ab8b-0b03-478c-96e0-e3a01af29828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account Opened!</value>
      <webElementGuid>329d9336-57b5-4241-8d30-c663a5128c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightPanel&quot;)/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/h1[@class=&quot;title&quot;]</value>
      <webElementGuid>a5d9d443-e3ea-4767-b239-a2171191b9cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/h1</value>
      <webElementGuid>f337363b-83a2-44ff-95cf-eb478a494736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>196d207b-1984-4800-9e23-ba54a7538ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Account Opened!' or . = 'Account Opened!')]</value>
      <webElementGuid>26574f3b-d4fc-41e4-8d96-1562f56de1db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
