<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblAccountTypeQuestion</name>
   <tag></tag>
   <elementGuidId>24b1c3d8-c4d3-4d47-8577-adf3f8f28c93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form.ng-pristine.ng-valid > p > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rightPanel']/div/div/form/p/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>fa38d3c6-fcab-4392-b2e9-9e558c306d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>What type of Account would you like to open?</value>
      <webElementGuid>4565d959-b6ec-480b-8df3-7c636af52e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightPanel&quot;)/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/form[@class=&quot;ng-pristine ng-valid&quot;]/p[1]/b[1]</value>
      <webElementGuid>5acb52f9-2dd1-4ade-980a-88685ef7cb88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/form/p/b</value>
      <webElementGuid>f92e9de2-64ca-47c0-a258-f60b4355da62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/p/b</value>
      <webElementGuid>bf019255-071e-452c-bea0-8a69da122005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'What type of Account would you like to open?' or . = 'What type of Account would you like to open?')]</value>
      <webElementGuid>a123e250-dad8-47c6-894c-2bfca938a7de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
