<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkLogOut</name>
   <tag></tag>
   <elementGuidId>ecb8e4ca-b748-4a5d-aae7-e2a25cb4d8a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(8) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='leftPanel']/ul/li[8]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bfecb514-eefa-478f-ab04-c6ec85a8bcea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/parabank/logout.htm</value>
      <webElementGuid>fca2bd7b-b089-4390-b83a-f0a56ca155d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log Out</value>
      <webElementGuid>66c71700-8e67-4f26-ac47-b2222f96dab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftPanel&quot;)/ul[1]/li[8]/a[1]</value>
      <webElementGuid>53123353-18ab-4621-b5a2-9dac4d88d82f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftPanel']/ul/li[8]/a</value>
      <webElementGuid>76329edc-6854-4ac0-a04f-a6d1e5c6001c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Log Out')]</value>
      <webElementGuid>530fc607-730b-4d18-9bef-ae9c56096580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/parabank/logout.htm')]</value>
      <webElementGuid>90d0b975-0789-4cff-ae82-05d629972dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a</value>
      <webElementGuid>fafe9407-d500-4136-bd0d-21bfad1fb5a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/parabank/logout.htm' and (text() = 'Log Out' or . = 'Log Out')]</value>
      <webElementGuid>61f4d4bd-109b-41ee-b7d3-da188c380ae4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
